#!/bin/sh

# POSIX shell doesn't support errtrace nor pipefail.

# Exit on error. Append "|| true" if you expect an error.
set -o errexit
# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR.
set -o nounset

BASE_DIR="$(dirname -- "$0")"
GVM_URL="https://bit.ly/46WnU6d"
GVM_LOCATION="$BASE_DIR/../bin/gvm"
INSTALL_URL="https://bit.ly/471yMzG"
INSTALL_LOCATION="$BASE_DIR/../bin/install"

for item in "$@"; do
  if [ "$item" = "$GVM_URL" ]; then
    cat "$GVM_LOCATION"
    return
  elif [ "$item" = "$INSTALL_URL" ]; then
    cat "$INSTALL_LOCATION"
    return
  fi
done

command "${REAL_CURL:?}" "$@"
